const fallbackList = [
  'recovery',
  'athlete',
  'grateful',
  'lift',
  'remark',
  'lay',
  'problem',
  'fashion',
  'recommend',
  'leave',
  'intention',
  'initiative',
  'orbit',
  'fascinate',
  'solo',
  'bottom',
  'copy',
  'program',
  'anger',
  'workshop',
  'wonder',
  'accountant',
  'duck',
  'captain',
  'bowel',
  'riot',
  'leadership',
  'definition',
  'cunning',
  'steak',
]

export const wordApiUrl = 'https://random-word-api.herokuapp.com/word?number=1&swear=0'
export default fallbackList